doc: avoid infinite recursion in hmModule
nix-community/nix-doom-emacs pull request #103
Opened 2022-04-03 00:45 UTC by edrex

when adding the home manager module to my HM config, i see:

```
error: infinite recursion encountered

       at /nix/store/g1562lf0ibiwj5d2ahz2prxy6dsxim7r-source/lib/modules.nix:403:28:

          402|         builtins.addErrorContext (context name)
          403|           (args.${name} or config._module.args.${name})
             |                            ^
          404|       ) (lib.functionArgs f);
```

This is discussed at https://github.com/vlaci/nix-doom-emacs/issues/157.

It occurs because somewhere in my home derivation, I'm referencing `config` (i think). By keeping modules separate using `mkMerge`, infinite recursion errors can be avoided.

2022-04-03 10:11 UTC, ckiee requested changes
Seems reasonable but I don't use flakes for NixOS, so cc @starcraft66 for review?

2022-04-03 10:11 UTC, ckiee commented on README.md
> +            { pkgs, ... }: {
```suggestion
            { ... }: {
```

2022-04-05 21:54 UTC, ModdedGamers commented
Fixing this works for me on both home-manager(non-NixOS), as well as NixOS(home-manager as NixOS Module).

2022-04-05 22:54 UTC, merged

2022-04-09 01:02 UTC, srid commented on README.md
> +            { ... }: {
I might be doing something wrong, but ... is this valid syntax? 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/3998/162550426-7b2c8336-2baf-42a1-a2f0-5087bba87171.png">

2022-04-09 01:08 UTC, srid commented on README.md
> +            { ... }: {
Okay, the whole things needs to be wrapped in `(..)`:

```nix
              ({ pkgs, ... }: {
                programs.doom-emacs = {
                  enable = true;
                  doomPrivateDir = ./config/doom.d;
                };
              })
```

However, now I get a different error:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/3998/162550606-0a4a54a0-a5fc-46df-b7c0-2b1e4803a5d5.png">

Note: this is all in macOS, with `darwin-rebuild`.